### ISSUE TITLE
User can create a review of a book.

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can create a review of a book they have read. 

## 📐 Functionality

> ##### A description of how the application will work from the user's perspective.

- [x] User can enter book title and author information.
- [x] User can enter the name of the book series (if any).
- [x] User can enter the name of the publisher.
- [x] User can enter the genres of the book matter.
- [x] User can click a button to add book reviews to their Goodreads account.
- [x] Users can upload an image of the book they're reviewing.
- [x] User can add the book synopsis.
- [x] User can write a review of a book.
- [x] User can select a rating of one to five stars. 
- [x] User can save their review.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-19 at 11 55 55 AM](https://github.com/tiffanydbrown/Bookish/assets/139157669/21e278e4-7a70-40f9-9a78-12036d63baac)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to  allow database to update the date with each review entry.

### ☁️ Server Tasks

- [x] Update `server.js` to get posts.
- [x] Update `server.js` to get a post by id.
- [x] Update `server.js` to make a post.
- [x] Update `server.js` to update a post.
- [x] Update `server.js` to delete a post.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to navigate the site.
- [x] Create a component to enter book information.
- [x] Create a component to write a book review.
- [x] Create a component to rate a book review.
- [x] Create a component for a Header.
- [x] Create a logo component.
- [x] Create a component for the review page layout.
- [x] Update a component to include the date of review for entries.
- [x] Add Routes for the site to navigate.
- [ ] 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
