### ISSUE TITLE
User Can Sign In 

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign in to the application.
Users can sign up to use the application.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-25 at 3 26 22 PM](https://github.com/tiffanydbrown/Bookish/assets/139157669/5b51a5b2-e6d1-4c93-92b8-723cb90b849f)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to register new users to the application.
- [x] Test with local storage site.
- [x] Add authorization middleware to the server. 
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the `Footer`.
- [x] Check that new users can log in to the site.
- [x] Make `fetch` requests to the server to allow users to sign in.
- [x] Make `fetch` requests to the server to allow users to sign up.
- [x] Create `routes` for the `sign in` and the `sign up` modal.
- [x] Create a component for the `sign-in`
- [x] Create a modal for the `sign up`
- [x] Update `App.ts` to set `Footer ' for each page.
- [x] Make sure the `Sign Up` button is tied to the api-registration request.
- [x] Make sure the `Sign In` button is tied to the api-authentication and api-authorization requests.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Ensure no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
