### ISSUE TITLE
User Can Update a Review 

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality
Users can update a review.

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-26 at 4 31 47 PM](https://github.com/tiffanydbrown/Bookish/assets/139157669/50969a37-e3c6-43dc-a56e-8fccba49dbf7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `data.ts` for PUT authorization.
- [x] Update `Post.tsx` with an edit link.
- [x] Add conditional statement to`Review.tsx` that will say what to do if a post is already populated. 

### 🧑‍⚕️ Clean Up Tasks

 

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
