### ISSUE TITLE
User can delete a review

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a review

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can delete a review.
The Home page and Review page will no longer display deleted reviews. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-29 at 4 00 58 PM](https://github.com/tiffanydbrown/Bookish/assets/139157669/5a8a3997-7857-41e3-955d-bb506f725e88)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a NewReview page.
- [x] Create a `Router` to NewReview page.
- [x] Change the link for new reviews.
- [x] Create `DeleteReview' FETCH request.
- [x] Create a `handleDelete` function in `Review`.
- [x] Update `NewReview` JSX to include a link to `Delete Review`.
- [x] Update `Edit` link to `Edit Review`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
