### ISSUE TITLE
User Can View Posts in Carousel

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can View Posts in the Carousel

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The most recent highest-rated posts (up to 5) will be displayed in the carousel on the landing page.
User will be able to navigate through posts using the prev and next arrows on the carousel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Update component to auto-rotate through images.
- [ ] Update the component to display the most recent highest-rated reviews.
- [ ] Make the reviews displayed clickable from the carousel.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented-out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
