### ISSUE TITLE
User Can View All Book Review Posts

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users Can View All Book Review Posts.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- [ ] Users can view their posts on the landing page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-23 at 12 26 01 PM](https://github.com/tiffanydbrown/Bookish/assets/139157669/9320ac7d-bf33-4e2c-803c-bc5df7a59277)   

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include review image and rating.

### ☁️ Server Tasks

- [x] Handle all errors and respond to the client
- [x] Updated server to include review image and rating in `post` and `put` requests.

### ⚡ Client Tasks

- [x] Create a component for a carousel of the book reviews
- [x] Create a component (Hero) to display posted reviews
- [x] Make reviews link to posts in the database.
- [x] Create a divider component to divide each post
- [x] Create a Landing page that contains the carousel and the five latest reviews.
- [x] Create a `data.ts` to fetch to the database for all the reviews.
- [x] Update the ReviewSnippet page to display saved reviews on the `Home` page.
- [x] Update the `Rating Component` to save to the database correctly.
- [x] Correct the routes in `App.tsx`.
=

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
