### ISSUE TITLE
User Can View Review Post

### ISSUE THREAD

**Issue by tiffanydbrown** [tiffanydbrown/Bookish#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can View Review Post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the `Read More` button on the `Home` page to read the complete book review.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-23 at 2 41 46 PM](https://github.com/tiffanydbrown/Bookish/assets/139157669/db659239-1e99-4a57-bba2-6ecd37de4d7b)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a page (ReadMore) to display the review (layout)
- [x] Create a component to display the book info for review. (ReadMoreInfo)
- [x] Create a component to display the book review. (ReadMoreReview)
- [x] Update page to fetch book information from the database. 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Ensure no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure all click targets show a `cursor: pointer` when hovering with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
